config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    path:'',
    path_name: {sign_in: "login", sign_out: "logout", edit: "profile", sigh_up: "registration"},
    controllers: {omniauth_callbacks: "omniauth_callbacks", registrations: "registrations"}
  resources :users, only: :show
  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
    end
    resources :photos, only: [:create, :destroy]
  end
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :room

  has_attached_file :image,
  styles: { medium: "300x300>", thumb: "100x100>" },
  default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image,
  content_type: /\Aimage\/.*\z/
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :photos

  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :accommodate, presence: true
  validates :bed_room, presence: true

  def cover_photo(size)
  if self.photos.length > 0
        self.photos[0].image.url(size)
  else "blank.jpg"
     end
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  validates :fullname, length: {maximum: 50}
  has_many :rooms
  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first
    if user
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.fullname = auth.info.name   # assuming the user model has a name
        user.fbprofile = auth.info.image # assuming the user model has an image
        # If you are using confirmable and the provider(s) you use validate emails,
        # uncomment the line below to skip the confirmation emails.
        user.uid = auth.uid
        user.provider = auth.provider
        #user.skip_confirmation!
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameter, if: :devise_controller?

  protected

  def configure_permitted_parameter
    devise_parameter_sanitizer.permit :sign_up, keys: [:fullname]
    devise_parameter_sanitizer.permit :account_update, keys: [:fullname, :phone_number, :description]
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def create
    @room = Room.find(params[:room_id])
    if params[:images]
      params[:images].each do |img|
        @room.photos.create(image: img)
      end

      @photos = @room.photos
      redirect_back(fallback_location: request.referer, notice: "Success...")
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @room = @photo.room

    @photo.destroy
    @photos = Photo.where(room_id: @room.id)
    respond_to :js
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, except: [:index, :new, :create]
  before_action :authenticate_user!, except: :show

  def index
    @rooms = current_user.rooms
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room= current_user.rooms.build(room_params)
    if @room.save
      redirect_to listing_room_path(@room), notice: "Saved Success"
    else
      flash[:alert] = @room.errors.full_messages
      render :new
    end
  end

  def listing
  end

  def pricing
  end

  def description
  end

  def photo_upload
    @photos = @room.photos
  end
  def show
    @photos = @room.photos
  end
  def amenities
  end

  def location
  end

  def update
    if @room.update(room_params)
      flash[:notice] = "Saved..."
    else
      flash[:alert] = @room.errors.full_messages
    end
    redirect_back(fallback_location: request.referer)
  end

  private
  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:home_type, :room_type, :accommodate, :bed_room,
     :listing_name, :summary, :address, :is_kitchen, :is_air, :is_heating, :is_internet, :is_tv,
      :price, :active)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def avatar(user)
    if user.fbprofile
      "https://graph.facebook.com/#{user.uid}/picture?type=large"
    else
      gravatar_id = Digest::MD5::hexdigest(user.email).downcase
      "https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identical&=150"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-abeli navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path do %>
        <%= image_tag "icon.png", size: "80", class: "navbar-brand" %>
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#">Blogs</a></li>
        <li><a href="#">Menu</a></li>
        <li><a href="#">Tips</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= image_tag avatar(current_user), class: "img-circle avatar-small"  %>&nbsp;
              <%= current_user.fullname %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", edit_user_registration_path %></li>
              <li><%= link_to "Settings", "#" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Signup", new_user_registration_path, class: "fa fa-user" %></a></li>
          <li><%= link_to "Login", new_user_session_path, class: "fa fa-sign-in" %></a></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbnb</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <%= render "layouts/nav" %>
    <%= render "shared/message" %>
    <div class="container main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/photos/_photos_list.html.erb
<% if @photos.count > 0 %>
<br/><br/>
<div id="photo">
  <div class="row">
    <% @photos.each do |photo| %>
    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading preview">
          <%= image_tag photo.image.url(:thumb) %>
        </div>
        <div class="panel-body">
          <span class="pull-right">
            <%= link_to room_photo_path(photo.room_id, photo), remote: true,
            method: :delete, data: {confirm: "Are you sure?"} do %>
            <i class="fa fa-trash-o fa-lg" aria-hidden="true"></i>
            <% end %>
          </span>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<% end %>

app/views/photos/destroy.js.erb
$('#photo').html("<%= j render 'photos_list' %>")

app/views/rooms/_room_menu.html.erb
<ul class="sidebar-link">
  <li class="sidebar-item">
    <%= link_to "Listing", listing_room_path, class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "Pricing", pricing_room_path, class: "sidebar-link active" %>
    <% if !@room.price.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Description", description_room_path, class: "sidebar-link active" %>
    <% if !@room.listing_name.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Photos", photo_upload_room_path, class: "sidebar-link active" %>
    <% if !@room.photos.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Amenities", amenities_room_path, class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "Location", location_room_path, class: "sidebar-link active" %>
    <% if !@room.address.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
</ul>
<% is_ready = !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank? %>
<%= form_for @room do |f| %>
  <%= f.hidden_field :active, value: true %>
  <%= f.submit "Publish", id: "publish_button", class: "btn btn-success btn-block",
  disabled: !is_ready %>
<% end %>

app/views/rooms/amenities.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading"> Amenities </div>
      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>
          <div class="row form-group">
            <div class="col-md-3">
              <%= f.check_box :is_tv %> TV
            </div>
            <div class="col-md-3">
              <%= f.check_box :is_kitchen %> Kitchen
            </div>
            <div class="col-md-3">
              <%= f.check_box :is_internet %> Internet
            </div>
          </div>

          <div class="row form-group">
            <div class="col-md-3">
              <%= f.check_box :is_heating %> Heating
            </div>
            <div class="col-md-3">
              <%= f.check_box :is_air %> Air Conditioning
            </div>
          </div>
          <br/>
          <br/>
          <div class="text-center">
            <%= f.submit "Save", class: "btn btn-form" %>
          </div>

          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/rooms/create.html.erb
<h1>Rooms#create</h1>
<p>Find me in app/views/rooms/create.html.erb</p>

app/views/rooms/description.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading"> Description </div>
      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>
          <div class="row">
            <div class="col-md-8">
              <div class="form-group">
                <label>Listing name</label>
                <%= f.text_field :listing_name, placeholder: "What is your listing name?", class: "form-control", required: true %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-8">
              <div class="form-group">
                <label>Summary</label>
                <%= f.text_area :summary, rows: 5, placeholder: "Summary of your house", class: "form-control", required: true %>
              </div>
            </div>
          </div>
          <div class="text-center">
            <%= f.submit "Save", class: "btn btn-form" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="row">
<div class="col-md-3">
  <ul class="sidebar-list">
      <li class="sidebar-item">
         <%= link_to "Your Listings", rooms_path, class: "sidebar-link active" %>    </li>
    </ul>
</div>
<div class="col-md-9">
  <div class="panel panel-default">
    <div class="panel-heading"> Listings </div>
    <div class="panel-body">
        <% @rooms.each do |room| %>
        <div class="row">
          <div class="col-md-2">
         <!--<%= image_tag room.photos[0].image.url(:thumb) if room.photos.length > 0 %> -->
         <%= image_tag room.cover_photo(:thumb) %>
          </div>
          <div class="col-md-7">
          <h4><%= room.listing_name %></h4> </div>
          <div class="col-md-3 right">
          <%= link_to "Update", listing_room_path(room), class: "btn btn-form" %>
          </div>
          </div>
        <hr/>
        <% end %>
    </div>
</div>
</div>
</div>

app/views/rooms/listing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading"> Listing
      </div>
      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>
          <div class="row">
            <div class="col-md-4 select">
              <div class="form-group">
                <label>Home Type</label>
                <%= f.select :home_type, [["Apartment", "Apartment"], ["House", "House"], ["Bed & Breakfast", "Bed & Breakfast"]], id: "home_type", prompt: "Select...", class: "form-control" %>
              </div>
            </div>
            <div class="col-md-4 select">
              <div class="form-group">
                <label>Room Type</label>
                <%= f.select :room_type, [["Entire", "Entire"], ["Private", "Private"], ["Shared", "Shared"]], id: "room_type", prompt: "Select...", class: "form-control" %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4 select">
              <div class="form-group">
                <label>Accommodate</label>
                <%= f.select :accommodate, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]], id: "accommodate", prompt: "Select...", class: "form-control" %>
              </div>
            </div>
            <div class="col-md-4 select">
              <div class="form-group">
                <label>Bedrooms</label>
                <%= f.select :bed_room, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]], id: "bed_room", prompt: "Select...", class: "form-control" %>
              </div>
            </div>
          </div>
          <%= f.submit "Save", class: "btn btn-normal" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/location.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading"> Location
      </div>
      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>
          <div class="row">
            <div class="col-md-8">
              <div class="form-group">
                <label>Address</label>
                <%= f.text_field :address, placeholder: "What is your address?", class: "form-control", required: true, id: "autoaddress" %>
              </div>
            </div>
          </div>
          <div class="text-center">
            <%= f.submit "Save", class: "btn btn-form" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading"> Create your beautiful place
  </div>
  <div class="panel-body">
    <div class="container">
      <%= form_for @room do |f| %>
      <div class="row">
        <div class="col-md-5 select">
          <div class="form-group">
            <label>Home Type</label>
            <%= f.select :home_type, [["Apartment", "Apartment"], ["House", "House"], ["Bed & Breakfast", "Bed & Breakfast"]],id: "home_type", prompt: "Select...", class: "form-control" %>
          </div>
        </div>
        <div class="col-md-5 select">
          <div class="form-group">
            <label>Room Type</label>
            <%= f.select :room_type, [["Entire", "Entire"], ["Private", "Private"], ["Shared", "Shared"]],id: "room_type", prompt: "Select...", class: "form-control" %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-5 select">
          <div class="form-group">
            <label>Accommodate</label>
            <%= f.select :accommodate, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]], id: "accommodate", prompt: "Select...", class: "form-control" %>
          </div>
        </div>
        <div class="col-md-5 select">
          <div class="form-group">
            <label>Bedrooms</label>
            <%= f.select :bed_room, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],id: "bed_room", prompt: "Select...", class: "form-control" %>
          </div>
        </div>
      </div>
      <div>
        <%= f.submit "Create My Room", class: "btn btn-normal" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/rooms/photo_upload.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading"> Photos </div>
      <div class="panel-body">
        <div class="container">
          <div class="row">
            <div class="col-md-offset-3 col-md-6">
              <!-- PHOTOS UPLOAD will to be continue -->
              <%= form_for @room, url: room_photos_path(@room), method: 'post', html: {multipart: true} do |f| %>
                <div class="row">
                  <div class="form-group">
                  <span class="btn btn-default btn-file text-babu">
                  <i class="fa fa-cloud-upload" aria-hidden="true"></i> Select Photos
                  <%= file_field_tag "images[]", type: :file, multiple: true %>
                </span>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit "Add Photos", class: "btn btn-form" %>
            </div>
            <% end %>
            </div>
            <%= render "photos/photos_list" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/pricing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading"> Pricing
      </div>
      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>
          <div class="row">
            <div class="col-md-8">
              <div class="form-group">
                <label>Price ($)</label>
                <%= f.text_field :price, placeholder: "eg:($100)", class: "form-control", required: true %>
              </div>
            </div>
          </div>
          <div class="text-center">
            <%= f.submit "Save", class: "btn btn-form" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="row">
  <div class="col-md-12">
    <%= image_tag @room.cover_photo(nil),width:"100%" %>
  </div>
</div>
<div class="row">
  <div class="col-md-8">
    <div class="row">
      <div class="col-md-8">
        <h1><%= @room.listing_name %></h1>
        <%= @room.address %>
      </div>
      <div class="col-md-4">
        <%= image_tag avatar(@room.user), class:"img-circle" %>            <br/><br/>
        <%= @room.user.fullname %>
      </div>
    </div>
    <hr>
  </div>
  <div class="col-md-4">
  </div>
</div>
<hr>
<div class="row text-babu ">
  <div class="row text-center row-space-1">
    <div class="col-md-3">
      <i class="fa fa-home fa-2x"></i>
    </div>
    <div class="col-md-3">
      <i class="fa fa-user-circle-o fa-2x"></i>
    </div>
    <div class="col-md-3">
      <i class="fa fa-bath fa-2x"></i>
    </div>
    <div class="col-md-3">
      <i class="fa fa-bed fa-2x"></i>
    </div>
  </div>
  <div class="row text-center">
    <div class="col-md-3">
      <%= @room.home_type %>
    </div>
    <div class="col-md-3">
      <%= pluralize(@room.accommodate,"Guest") %>
    </div>
    <div class="col-md-3">
      <%= pluralize(@room.bed_room,"Guest") %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <h3>About Listing</h3>
    <p><%= raw(@room.summary) %></p>
  </div>
</div>
<div class="row">
  <div class="col-md-3">
    <h4>Amenities</h4>
  </div>
  <div class="col-md-9">
    <div class="col-md-6">
      <ul class="amenities">
        <li class="<%= 'text-line-through' if !@room.is_tv %>" >TV</li>
        <li class="<%= 'text-line-through' if !@room.is_kitchen %>" >Kitchen</li>
        <li class="<%= 'text-line-through' if !@room.is_internet %>">Internet</li>
      </ul>
    </div>
    <div class="col-md-6">
      <ul class="amenities">
        <li class="<%= 'text-line-through' if !@room.is_heating %>">Heating</li>
        <li class="<%= 'text-line-through' if !@room.is_air %>">Air Condition</li>
      </ul>
    </div>
  </div>
</div>
<div class="row">
  <% if @photos.length > 0 %>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <% @photos.each do |photo| %>
      <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
      <% end %>
    </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <% @photos.each do |photo| %>
      <div class="item <%= 'active' if @photos[0].id  == photo.id %>">
        <%= image_tag photo.image.url() %>
      </div>
      <% end %>
    </div>
    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
    </a>
  </div>
  <% end %>
</div>

app/views/rooms/update.html.erb
<h1>Rooms#update</h1>
<p>Find me in app/views/rooms/update.html.erb</p>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
<script type="text/javascript">
  <% flash.each do | key, value| %>
  <% type = key.to_s.gsub('alert','error').gsub('notice','success') %>
  toastr['<%= type %>']('<%= value %>')
  <% end %>
</script>
<% end %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="text-center">
      <%= image_tag avatar(@user), class: "img-circle avatar-full" %>
    </div>
    <div class="panel panel-success">
      <div class="panel-heading">
        Verfication
      </div>
      <div class="panel-body">
        Email address<br/>
        Phone number
      </div>
    </div>
  </div>
  <div class="col-md-9">
    <h2><%= @user.fullname %></h2>
    <%= @user.description %>
  </div>
</div>